<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260214152207 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE location (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, building_number VARCHAR(50) NOT NULL, unit_room VARCHAR(50) DEFAULT NULL, street_id INT NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5E9E89CB87CF8EB ON location (street_id)');
        $this->addSql('CREATE INDEX IDX_5E9E89CB7E3C61F9 ON location (owner_id)');
        $this->addSql('ALTER TABLE location ADD CONSTRAINT FK_5E9E89CB87CF8EB FOREIGN KEY (street_id) REFERENCES street (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE location ADD CONSTRAINT FK_5E9E89CB7E3C61F9 FOREIGN KEY (owner_id) REFERENCES owner (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE location DROP CONSTRAINT FK_5E9E89CB87CF8EB');
        $this->addSql('ALTER TABLE location DROP CONSTRAINT FK_5E9E89CB7E3C61F9');
        $this->addSql('DROP TABLE location');
    }
}
