<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260210132030 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE reading (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, water_meter_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C11AFC41DFD32D9D ON reading (water_meter_id)');
        $this->addSql('CREATE TABLE water_meter (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, serial_number VARCHAR(255) NOT NULL, location VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE reading ADD CONSTRAINT FK_C11AFC41DFD32D9D FOREIGN KEY (water_meter_id) REFERENCES water_meter (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE reading DROP CONSTRAINT FK_C11AFC41DFD32D9D');
        $this->addSql('DROP TABLE reading');
        $this->addSql('DROP TABLE water_meter');
    }
}
